version: "3"
services:
  fe:
    image: apache/doris:fe-3.0.4
    hostname: fe
    environment:
     - FE_SERVERS=fe1:127.0.0.1:9010
     - FE_ID=1
    network_mode: host
  be:
    image: apache/doris:be-3.0.4
    hostname: be
    environment:
     - FE_SERVERS=fe1:127.0.0.1:9010
     - BE_ADDR=127.0.0.1:9050
    depends_on:
      - fe
    network_mode: host
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - fe
      - be
    network_mode: host
  frontend:
    build: ./frontend
    ports:
      - "3500:3000"
    depends_on:
      - backend
    network_mode: host
